services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  app:
    build:
      context: ../ushort
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped